#-------------------------------
# General Site Settings
title: YwjXx Blog
# logo: logo.jpg # You can add own logo.
description: Xiang Xu's Blog


#-------------------------------
# Author Settings
author:
  name: Xiang Xu
  image: profile.jpeg
  say-hello: Hello I'm <strong>Xiang Xu</strong>
  bio: Come from China ğŸ‡¨ğŸ‡³ and living in Ireland ğŸ‡®ğŸ‡ª at moment <br/>
       Software Engineer ğŸ‘¨â€ğŸ’» <br/>
       I like technology ğŸ’» , sports ğŸ€ , travelling ğŸ§³  and photography ğŸ“· 
      


#-------------------------------
# Contact links
# twitter: https://twitter.com/ # Add your Twitter handle
# dribbble: https://dribbble.com/ # Add your Dribbble handle
# pinterest: https://pinterest.com/ # Add your Pinterest handle
instagram: https://www.instagram.com/xiangxu_/ # Add your Instagram handle
facebook: https://www.facebook.com/profile.php?id=100004084192117 # Add your Facebook handle
github: https://github.com/XiangXu
linkedin: https://www.linkedin.com/in/xiang-xu-2a106271/


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: xiangxu_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: UA-178905804-1 # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e